name: List Available macOS Releases

on:
  schedule:
    - cron: "0 0 * * 2"

jobs:
  get-context-variables:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Context Variables
        run: echo "${{ toJson(github) }}"
  list-installers:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: List Installers
        run: |
          sudo "/System/Library/PrivateFrameworks/Seeding.framework/Versions/Current/Resources/seedutil" enroll DeveloperSeed
          sleep 5
          softwareupdate
          softwareupdate --list-full-installers
  # send-email:
  #   - name: Send mail
  #     uses: dawidd6/action-send-mail@v3
  #     with:
  #       server_address: smtp.gmail.com
  #   # Required mail server port:
  #       server_port: 465
  #   # Optional (recommended): mail server username:
  #       username: ${{secrets.MAIL_USERNAME}}
  #   # Optional (recommended) mail server password:
  #       password: ${{secrets.MAIL_PASSWORD}}
  #   # Required mail subject:
  #       subject: Github Actions job result
  #   # Required recipients' addresses:
  #       to: obiwan@example.com,yoda@example.com
  #   # Required sender full name (address can be skipped):
  #       from: Luke Skywalker # <user@example.com>
  #   # Optional whether this connection use TLS (default is true if server_port is 465)
  #       secure: true
  #   # Optional plain body:
  #       body: Build job of ${{github.repository}} completed successfully!
  #   # Optional HTML body read from file:
  #       html_body: file://README.html
  #   # Optional carbon copy recipients:
  #       cc: kyloren@example.com,leia@example.com
  #   # Optional blind carbon copy recipients:
  #       bcc: r2d2@example.com,hansolo@example.com
  #   # Optional recipient of the email response:
  #       reply_to: luke@example.com
  #   # Optional Message ID this message is replying to:
  #       in_reply_to: <random-luke@example.com>
  #   # Optional unsigned/invalid certificates allowance:
  #       ignore_cert: true
  #   # Optional converting Markdown to HTML (set content_type to text/html too):
  #       convert_markdown: true
  #   # Optional attachments:
  #       attachments: attachments.zip,git.diff,./dist/static/*.js
  #   # Optional priority: 'high', 'normal' (default) or 'low'
  #       priority: normal
